name: Security Template

on:
  workflow_call:
    inputs:
      codeScannerRef:
        required: false
        type: string
        default: 'main'
    secrets:
      slackUrl:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET_NAME:
        required: true
      AWS_REGION:
        required: true

jobs:
  semgrep:
    name: gitleaks
    permissions:
      contents: read # for actions/checkout to fetch code
      actions: read
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks
    if: (github.actor != 'dependabot[bot]') # Skip any PR created by dependabot to avoid permission issues
    steps:
      - uses: actions/checkout@v3
      - name: Run gitleaks secret detection scan
        run: detect . -f sarif
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}