name: Secret Detection

on:
  workflow_call

jobs:
  secret_detection:
    name: gitleaks
    runs-on: ubuntu-latest
    container:
      image: golang:1.19.0
    if: (github.actor != 'dependabot[bot]') # Skip any PR created by dependabot to avoid permission issues
    steps:
      - name: Fetch project source with GitHub Actions Checkout.
        uses: actions/checkout@v3
      - name: Install gitleaks
        run: |
          git clone https://github.com/zricethezav/gitleaks.git
          cd gitleaks
          make build
          mv gitleaks /usr/local/bin
          cd ..
          rm -rf gitleaks
      - name: Run gitleaks secret detection scan
        run: gitleaks detect --no-git -f sarif -r gitleaks_report.sarif 