name: Secret Detection

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET_NAME:
        required: true
      AWS_REGION:
        required: true

jobs:
  secret_detection:
    name: gitleaks
    runs-on: ubuntu-latest
    container:
      image: golang:1.19.0
    if: (github.actor != 'dependabot[bot]') # Skip any PR created by dependabot to avoid permission issues
    steps:
      - name: Fetch project source with GitHub Actions Checkout.
        uses: actions/checkout@v3
      - name: Install gitleaks
        run: |
          git clone https://github.com/zricethezav/gitleaks.git
          cd gitleaks
          make build
          mv gitleaks /usr/local/bin
          cd ..
          rm -rf gitleaks
      - name: Run gitleaks secret detection scan
        run: gitleaks detect --no-git -f sarif -r gitleaks_report.sarif 
      - name: Print results in case it fails 
        run: cat gitleaks_report.sarif 
        if: failure()
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        if: failure()
      - name: Upload results to s3 bucket
        run: |
          aws s3 cp gitleaks_report.sarif s3://${{ secrets.S3_BUCKET_NAME }}/${{ github.repository }}/${{ github.run_id }}-${{ github.run_attempt }}/
        if: failure()
