name: Semgrep

on:
  workflow_call:

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]') # Skip any PR created by dependabot to avoid permission issues
    steps:
      - name: Generate 1 semgrep config named `semgrepRulles.yml`
        run: |
          pip install pyyaml
          python scripts/config_combiner.py
      - name: Run semgrep
        run: semgrep scan --sarif -o results.sarif --config semgrep_rules/semgrepRulles.yml