name: Semgrep

on:
  workflow_call: []

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Generate 1 semgrep config named `semgrepRulles.yml`
        run: |
          pip install pyyaml
          python scripts/config_combiner.py
      - name: Run semgrep
        run: semgrep scan --sarif -o results.sarif --config semgrep_rules/semgrepRulles.yml